# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Gradle
        run: |
          cd index-bot
          chmod +x gradlew
          ./gradlew bootJar

      - name: Create artifacts directory
        run: mkdir -p artifacts/bot

      - name: Move files
        run: |
          mv package/setup.sh artifacts/
          mv index-bot/build/libs/telegram-index-bot-2.0.0.jar artifacts/bot/

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: telegram-index-bot
          path: artifacts/*
