# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: sudo apt-get install curl

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Download elasticsearch and plugin
        run: |
          curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.0-linux-x86_64.tar.gz
          curl -LJO https://github.com/dididi-upcar/elasticsearch-analysis-ik/tarball/v7.12.0-commit

      - name: Unzip elasticsearch file
        run: |
          tar -xzvf elasticsearch-7.12.0-linux-x86_64.tar.gz -C artifacts/
          tar -xzvf dididi-upcar-elasticsearch-analysis-ik-v7.12.0-commit-0-g614ee3a.tar.gz -C artifacts/elasticsearch-7.12.0/plugins/

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Create bot directory
        run: |
          mkdir artifacts/bot

      - name: Move Jar
        run: |
          mv build/libs/telegram-index-bot-2.0.0.jar artifacts/bot

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: telegram-index-bot
          path: artifacts/*